from google.auth.environment_vars import AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY

MONGODB_URL_KEY = "MONGODB_URL"
AWS_ACCESS_KEY_ID_ENV_KEY = "AWS_ACCESS_KEY_ID"
AWS_SECRET_ACCESS_KEY_ENV_KEY = "AWS_SECRET_ACCESS_KEY"
REGION_NAME = "us-east-1"